/// Centralized backend exception mappings

class BackendException implements Exception {
  final String code;
  final String message;

  const BackendException(this.code, this.message);

  @override
  String toString() => 'BackendException(\$code): \$message';
}

/// Known error codes generated by Supabase Edge Functions:
class BackendErrorCodes {
  static const insufficientCredits = 'INSUFFICIENT_CREDITS';
  static const linkedAccountRequired = 'LINKED_ACCOUNT_REQUIRED';
  static const unknown = 'UNKNOWN';
  static const functionError = 'FUNCTION_ERROR';
}
